// src/auth/role-permissions.map.ts
import { Role } from './roles.enum';
import { Resource, Action } from './permissions.enum';

export const RolePermissions: Record<
  Role,
  { resource: Resource; action: Action }[]
> = {
  [Role.ADMINISTRATOR]: [
    { resource: Resource.USERS, action: Action.CREATE },
    { resource: Resource.USERS, action: Action.UPDATE },
    { resource: Resource.USERS, action: Action.DELETE },
    { resource: Resource.USERS, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.CREATE },
    { resource: Resource.WAREHOUSES, action: Action.UPDATE },
    { resource: Resource.WAREHOUSES, action: Action.DELETE },
    { resource: Resource.REPORTS, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.UPDATE },
    { resource: Resource.STOCKENTRIES, action: Action.DELETE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],

  [Role.MANAGER]: [
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.CREATE },
    { resource: Resource.WAREHOUSES, action: Action.UPDATE },
    { resource: Resource.WAREHOUSES, action: Action.DELETE },
    { resource: Resource.REPORTS, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.UPDATE },
    { resource: Resource.STOCKENTRIES, action: Action.DELETE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
    // ❌ No tiene acceso a administrar usuarios
  ],

  [Role.ASSISTANT]: [
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],

  [Role.CHEF]: [
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],
};
