import { Resource } from '../shared/enums/resource.enum';
import { Action } from '../shared/enums/action.enum';

import { UserRole } from '../shared/enums/user-role.enum';

export const RolePermissions: Record<
  UserRole,
  { resource: Resource; action: Action }[]
> = {
  [UserRole.ADMINISTRATOR]: [
    { resource: Resource.USERS, action: Action.CREATE },
    { resource: Resource.USERS, action: Action.UPDATE },
    { resource: Resource.USERS, action: Action.DELETE },
    { resource: Resource.USERS, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.CREATE },
    { resource: Resource.WAREHOUSES, action: Action.UPDATE },
    { resource: Resource.WAREHOUSES, action: Action.DELETE },
    { resource: Resource.REPORTS, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.UPDATE },
    { resource: Resource.STOCKENTRIES, action: Action.DELETE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],

  [UserRole.MANAGER]: [
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.WAREHOUSES, action: Action.CREATE },
    { resource: Resource.WAREHOUSES, action: Action.UPDATE },
    { resource: Resource.WAREHOUSES, action: Action.DELETE },
    { resource: Resource.REPORTS, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.UPDATE },
    { resource: Resource.STOCKENTRIES, action: Action.DELETE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
    // ❌ No tiene acceso a administrar usuarios
  ],

  [UserRole.ASSISTANT]: [
    { resource: Resource.WAREHOUSES, action: Action.READ },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.CREATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.UPDATE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.DELETE },
    { resource: Resource.PRODUCTCATEGORIES, action: Action.READ },
    { resource: Resource.PRODUCTS, action: Action.CREATE },
    { resource: Resource.PRODUCTS, action: Action.UPDATE },
    { resource: Resource.PRODUCTS, action: Action.DELETE },
    { resource: Resource.PRODUCTS, action: Action.READ },
    { resource: Resource.STOCKENTRIES, action: Action.CREATE },
    { resource: Resource.STOCKENTRIES, action: Action.READ },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.UPDATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.DELETE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.STOCKLOSSES, action: Action.CREATE },
    { resource: Resource.STOCKLOSSES, action: Action.UPDATE },
    { resource: Resource.STOCKLOSSES, action: Action.DELETE },
    { resource: Resource.STOCKLOSSES, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],

  [UserRole.CHEF]: [
    { resource: Resource.STOCKWITHDRAWALS, action: Action.CREATE },
    { resource: Resource.STOCKWITHDRAWALS, action: Action.READ },
    { resource: Resource.INVENTORY, action: Action.READ },
  ],
};
